### ISSUE TITLE
training with sfm and init improvements

### ISSUE THREAD

**Issue by cv-lab-x** [KU-CVLAB/RAIN-GS#12]
hi, thanks for your great work, have you tested training with sfm points and your init improvements? cause sfm points are very sparse, there's no sfm point on lots of parts of the scene. will the results be more better if using both sfm points and your init improvements ?
@crepejung00  Looking forward to your reply, thanks.

**Comment by crepejung00** [comment]
Hi, thank you for your interest in our work! 

Actually, we didn't try out the setting you questioned and thought it was really interesting! Since most of the datasets that are used for evaluation (e.g., Mip-NeRF360) already contain dense point clouds, we currently do not have the results to answer your question. We will try it as soon as possible and share our results! 
BTW, we are currently a bit busy due to the Neurips submission deadline and have plans to update our paper and code for another significant performance boost even from random point clouds! Our current timeline is to refactor and release our new code in two weeks, so please stay tuned!

Thanks.

**Comment by crepejung00** [comment]
I will temporarily close this issue and reopen it when we are ready with the results to share! 
Thanks.
