### ISSUE TITLE
The experimental results are inconsistent with the results in the paper.

### ISSUE THREAD

**Issue by Yuhuoo** [KU-CVLAB/RAIN-GS#14]
I have run the command as described in your project without modifying any code, but the results obtained are different from those in your paper.

python train.py -s {dataset_path} --exp_name {exp_name} --eval --ours
|scene|PSNR|SSIM|LPIPS|
|---|---|---|---|
|train|20.96|0.76|0.27|
|truck|22.92|0.82|0.21|
|drjohnson|28.94 | 0.89 | 0.27 |
|playroom| 30.09 | 0.90 | 0.26 |

python train.py -s {dataset_path} --exp_name {exp_name} --eval --DSV
|scene|PSNR|SSIM|LPIPS|
|---|---|---|---|
|train|20.68|0.77|0.26|
|truck|20.08|0.75|0.25|
|drjohnson| 28.74| 0.89 | 0.26 |
|playroom| 28.53| 0.89| 0.27|

The result in your paper:
<img width="975" alt="image" src="https://github.com/KU-CVLAB/RAIN-GS/assets/91204817/ab269412-807f-4a53-aea5-1f1c6bd54859">

**Comment by crepejung00** [comment]
Hi, 
We tested our codes multiple times and verified that the codes faithfully reproduce the results on our paper. 
Although we haven't changed any random seeds for our experiment, due to the randomness in the PDF sampling in the split process of the adaptive density control of 3DGS, the results can differ about +- 0.2dB PSNR from the reported values. It seems that the results of all other scenes except the truck scene in the Tanks & Temples dataset are reasonable. 
In addition, we have re-cloned our repository and tried training the scenes you mentioned, and we have found that all scenes match the results on the table. Here are the results:
| scene      | PSNR  | SSIM | LPIPS |
|------------|-------|------|-------|
| train      | 21.089 | 0.756 | 0.271  |
| truck      | 23.478 | 0.833 | 0.200 |
| drjohnson  | 28.960 | 0.893 | 0.268  |
| playroom   | 30.139 | 0.902 | 0.258  |

Could you please try training the truck scene one more time and check if the dataset has not been modified from the original version, which is provided by Inria 3DGS [repo](https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/datasets/input/tandt_db.zip)?

Thanks,
Jaewoo.
