### ISSUE TITLE
Some questions about the Progressive Gaussian low-pass filter control and ABE-Split

### ISSUE THREAD

**Issue by JIANG-CX** [KU-CVLAB/RAIN-GS#15]
Wonderful work!

I have some questions about the effectiveness of the Progressive Gaussian low-pass filter control and the ABE-Split strategy:
1. Since you adopt SLV random initialization, each Gaussian already has a large covariance and covers a larger area. Why is it still necessary to further enlarge their coverage area using the low-pass filter?
2. I'm a bit confused about the ABE-Split strategy. It seems that you clone a new Gaussian to a distant area, but how do you ensure that this cloned Gaussian is positioned appropriately? 

Thanks.

**Comment by crepejung00** [comment]
Hi,
Sorry for the late reply, I was a bit busy due to other submissions.

1. Yes, your understanding is correct that the SLV random initialization already helps with the large coverage. However, when applying together with the naive optimization strategy with 3DGS, when the SLV initialized Gaussians are split, their covariance becomes smaller by a factor of 1.6 every time, and as this process is applied every 100 iters, this makes the SLV initialized Gaussians become very similar to the case of initializing Gaussians Dense + Small Variance. As we have aimed to design a strategy that can be applied in a plug-and-play manner, we wanted to make as few changes as possible to the original 3DGS optimization, we have adopted the Progressive Low-pass filter control which can **ensure** the Gaussians to learn from a large area in the image pixel space.

2. When understanding the 3DGS optimization strategy, the Gaussians can only receive the Gradients from areas near their coverage. This results in Gaussians initialized in random or noisy positions unable to receive the gradients from where the scene geometry is located, which can lead to under-reconstructed areas. To prevent this from happening, we can send Gaussians with large variances to places where the current existing Gaussians does not cover. This is our motivation of applying the ABE-Split in the early stages of optimization, which can effectively locate Gaussians to where the scene geometry exists by combining the ABE-Split and the SLV initialization. We have found that using the two strategies is essential. As you mentioned we can't ensure the Gaussians are located appropriately by the current ABE-Split algorithm but we have found that the pruning algorithm effectively prunes Gaussians where they shouldn't be located. Note that our methods act as a baseline strategy which effectively reveals why the Gaussians require accurate initial positions and what is required to reveal this property. We agree that the ABE-Split can be extended or improved to a more sophisticated algorithm.

Thanks!
